[build]
  # Frontend build settings
  base = "."
  publish = "frontend/build"
  command = "cd frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirect API calls to specific Netlify Functions
[[redirects]]
  from = "/api/v1/users/*"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/v1/assessment/*"
  to = "/.netlify/functions/assessment"
  status = 200

[[redirects]]
  from = "/api/v1/content/*"
  to = "/.netlify/functions/content"
  status = 200

[[redirects]]
  from = "/api/v1/analytics/*"
  to = "/.netlify/functions/content"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
